services:
  app:
    container_name: ikuyo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/web/node_modules
      - /app/packages/typescript/node_modules
