// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.19.6
// source: pkg/models/request.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GuestbookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuestbookRequest) Reset() {
	*x = GuestbookRequest{}
	mi := &file_pkg_models_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuestbookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuestbookRequest) ProtoMessage() {}

func (x *GuestbookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_models_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuestbookRequest.ProtoReflect.Descriptor instead.
func (*GuestbookRequest) Descriptor() ([]byte, []int) {
	return file_pkg_models_request_proto_rawDescGZIP(), []int{0}
}

func (x *GuestbookRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GuestbookRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GuestbookRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GuestbookNonGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuestbookNonGetRequest) Reset() {
	*x = GuestbookNonGetRequest{}
	mi := &file_pkg_models_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuestbookNonGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuestbookNonGetRequest) ProtoMessage() {}

func (x *GuestbookNonGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_models_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuestbookNonGetRequest.ProtoReflect.Descriptor instead.
func (*GuestbookNonGetRequest) Descriptor() ([]byte, []int) {
	return file_pkg_models_request_proto_rawDescGZIP(), []int{1}
}

func (x *GuestbookNonGetRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_pkg_models_request_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_models_request_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_pkg_models_request_proto_rawDescGZIP(), []int{2}
}

func (x *AuthRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AuthRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type DeleteUserByEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserByEmailRequest) Reset() {
	*x = DeleteUserByEmailRequest{}
	mi := &file_pkg_models_request_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserByEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserByEmailRequest) ProtoMessage() {}

func (x *DeleteUserByEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_models_request_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserByEmailRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserByEmailRequest) Descriptor() ([]byte, []int) {
	return file_pkg_models_request_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteUserByEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_pkg_models_request_proto protoreflect.FileDescriptor

const file_pkg_models_request_proto_rawDesc = "" +
	"\n" +
	"\x18pkg/models/request.proto\x12\x06models\"^\n" +
	"\x10GuestbookRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"(\n" +
	"\x16GuestbookNonGetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"?\n" +
	"\vAuthRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"0\n" +
	"\x18DeleteUserByEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05emailB\x19Z\x17ekel-backend/pkg/modelsb\x06proto3"

var (
	file_pkg_models_request_proto_rawDescOnce sync.Once
	file_pkg_models_request_proto_rawDescData []byte
)

func file_pkg_models_request_proto_rawDescGZIP() []byte {
	file_pkg_models_request_proto_rawDescOnce.Do(func() {
		file_pkg_models_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_models_request_proto_rawDesc), len(file_pkg_models_request_proto_rawDesc)))
	})
	return file_pkg_models_request_proto_rawDescData
}

var file_pkg_models_request_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_models_request_proto_goTypes = []any{
	(*GuestbookRequest)(nil),         // 0: models.GuestbookRequest
	(*GuestbookNonGetRequest)(nil),   // 1: models.GuestbookNonGetRequest
	(*AuthRequest)(nil),              // 2: models.AuthRequest
	(*DeleteUserByEmailRequest)(nil), // 3: models.DeleteUserByEmailRequest
}
var file_pkg_models_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_models_request_proto_init() }
func file_pkg_models_request_proto_init() {
	if File_pkg_models_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_models_request_proto_rawDesc), len(file_pkg_models_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_models_request_proto_goTypes,
		DependencyIndexes: file_pkg_models_request_proto_depIdxs,
		MessageInfos:      file_pkg_models_request_proto_msgTypes,
	}.Build()
	File_pkg_models_request_proto = out.File
	file_pkg_models_request_proto_goTypes = nil
	file_pkg_models_request_proto_depIdxs = nil
}
