// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.19.6
// source: pkg/models/response.proto

package models

import (
	entities "ekel-backend/pkg/entities"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type APIHomeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIHomeResponse) Reset() {
	*x = APIHomeResponse{}
	mi := &file_pkg_models_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIHomeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIHomeResponse) ProtoMessage() {}

func (x *APIHomeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_models_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIHomeResponse.ProtoReflect.Descriptor instead.
func (*APIHomeResponse) Descriptor() ([]byte, []int) {
	return file_pkg_models_response_proto_rawDescGZIP(), []int{0}
}

func (x *APIHomeResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *APIHomeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type APISuccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APISuccessResponse) Reset() {
	*x = APISuccessResponse{}
	mi := &file_pkg_models_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APISuccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APISuccessResponse) ProtoMessage() {}

func (x *APISuccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_models_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APISuccessResponse.ProtoReflect.Descriptor instead.
func (*APISuccessResponse) Descriptor() ([]byte, []int) {
	return file_pkg_models_response_proto_rawDescGZIP(), []int{1}
}

func (x *APISuccessResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *APISuccessResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type APISuccessGetGuestbookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*entities.Guestbook  `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APISuccessGetGuestbookResponse) Reset() {
	*x = APISuccessGetGuestbookResponse{}
	mi := &file_pkg_models_response_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APISuccessGetGuestbookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APISuccessGetGuestbookResponse) ProtoMessage() {}

func (x *APISuccessGetGuestbookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_models_response_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APISuccessGetGuestbookResponse.ProtoReflect.Descriptor instead.
func (*APISuccessGetGuestbookResponse) Descriptor() ([]byte, []int) {
	return file_pkg_models_response_proto_rawDescGZIP(), []int{2}
}

func (x *APISuccessGetGuestbookResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *APISuccessGetGuestbookResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *APISuccessGetGuestbookResponse) GetData() []*entities.Guestbook {
	if x != nil {
		return x.Data
	}
	return nil
}

type APIErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Stack         string                 `protobuf:"bytes,3,opt,name=stack,proto3" json:"stack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIErrorResponse) Reset() {
	*x = APIErrorResponse{}
	mi := &file_pkg_models_response_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIErrorResponse) ProtoMessage() {}

func (x *APIErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_models_response_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIErrorResponse.ProtoReflect.Descriptor instead.
func (*APIErrorResponse) Descriptor() ([]byte, []int) {
	return file_pkg_models_response_proto_rawDescGZIP(), []int{3}
}

func (x *APIErrorResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *APIErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *APIErrorResponse) GetStack() string {
	if x != nil {
		return x.Stack
	}
	return ""
}

type AuthAPISuccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AuthToken     string                 `protobuf:"bytes,3,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthAPISuccessResponse) Reset() {
	*x = AuthAPISuccessResponse{}
	mi := &file_pkg_models_response_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthAPISuccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthAPISuccessResponse) ProtoMessage() {}

func (x *AuthAPISuccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_models_response_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthAPISuccessResponse.ProtoReflect.Descriptor instead.
func (*AuthAPISuccessResponse) Descriptor() ([]byte, []int) {
	return file_pkg_models_response_proto_rawDescGZIP(), []int{4}
}

func (x *AuthAPISuccessResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *AuthAPISuccessResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AuthAPISuccessResponse) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

type AdminInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminInfoResponse) Reset() {
	*x = AdminInfoResponse{}
	mi := &file_pkg_models_response_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminInfoResponse) ProtoMessage() {}

func (x *AdminInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_models_response_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminInfoResponse.ProtoReflect.Descriptor instead.
func (*AdminInfoResponse) Descriptor() ([]byte, []int) {
	return file_pkg_models_response_proto_rawDescGZIP(), []int{5}
}

func (x *AdminInfoResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *AdminInfoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AdminInfoResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type APISuccessGetUserByEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*entities.User       `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APISuccessGetUserByEmailResponse) Reset() {
	*x = APISuccessGetUserByEmailResponse{}
	mi := &file_pkg_models_response_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APISuccessGetUserByEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APISuccessGetUserByEmailResponse) ProtoMessage() {}

func (x *APISuccessGetUserByEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_models_response_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APISuccessGetUserByEmailResponse.ProtoReflect.Descriptor instead.
func (*APISuccessGetUserByEmailResponse) Descriptor() ([]byte, []int) {
	return file_pkg_models_response_proto_rawDescGZIP(), []int{6}
}

func (x *APISuccessGetUserByEmailResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *APISuccessGetUserByEmailResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *APISuccessGetUserByEmailResponse) GetData() []*entities.User {
	if x != nil {
		return x.Data
	}
	return nil
}

type APISuccessGetWakatimeStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *entities.WakaTimeData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APISuccessGetWakatimeStatsResponse) Reset() {
	*x = APISuccessGetWakatimeStatsResponse{}
	mi := &file_pkg_models_response_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APISuccessGetWakatimeStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APISuccessGetWakatimeStatsResponse) ProtoMessage() {}

func (x *APISuccessGetWakatimeStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_models_response_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APISuccessGetWakatimeStatsResponse.ProtoReflect.Descriptor instead.
func (*APISuccessGetWakatimeStatsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_models_response_proto_rawDescGZIP(), []int{7}
}

func (x *APISuccessGetWakatimeStatsResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *APISuccessGetWakatimeStatsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *APISuccessGetWakatimeStatsResponse) GetData() *entities.WakaTimeData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_pkg_models_response_proto protoreflect.FileDescriptor

const file_pkg_models_response_proto_rawDesc = "" +
	"\n" +
	"\x19pkg/models/response.proto\x12\x06models\x1a\x1cpkg/entities/guestbook.proto\x1a\x17pkg/entities/user.proto\x1a\x1bpkg/entities/wakatime.proto\"L\n" +
	"\x0fAPIHomeResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"O\n" +
	"\x12APISuccessResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x84\x01\n" +
	"\x1eAPISuccessGetGuestbookResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x04data\x18\x03 \x03(\v2\x13.entities.GuestbookR\x04data\"c\n" +
	"\x10APIErrorResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05stack\x18\x03 \x01(\tR\x05stack\"r\n" +
	"\x16AuthAPISuccessResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x03 \x01(\tR\tauthToken\"d\n" +
	"\x11AdminInfoResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"\x81\x01\n" +
	" APISuccessGetUserByEmailResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\"\n" +
	"\x04data\x18\x03 \x03(\v2\x0e.entities.UserR\x04data\"\x8b\x01\n" +
	"\"APISuccessGetWakatimeStatsResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12*\n" +
	"\x04data\x18\x03 \x01(\v2\x16.entities.WakaTimeDataR\x04dataB\x19Z\x17ekel-backend/pkg/modelsb\x06proto3"

var (
	file_pkg_models_response_proto_rawDescOnce sync.Once
	file_pkg_models_response_proto_rawDescData []byte
)

func file_pkg_models_response_proto_rawDescGZIP() []byte {
	file_pkg_models_response_proto_rawDescOnce.Do(func() {
		file_pkg_models_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_models_response_proto_rawDesc), len(file_pkg_models_response_proto_rawDesc)))
	})
	return file_pkg_models_response_proto_rawDescData
}

var file_pkg_models_response_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pkg_models_response_proto_goTypes = []any{
	(*APIHomeResponse)(nil),                    // 0: models.APIHomeResponse
	(*APISuccessResponse)(nil),                 // 1: models.APISuccessResponse
	(*APISuccessGetGuestbookResponse)(nil),     // 2: models.APISuccessGetGuestbookResponse
	(*APIErrorResponse)(nil),                   // 3: models.APIErrorResponse
	(*AuthAPISuccessResponse)(nil),             // 4: models.AuthAPISuccessResponse
	(*AdminInfoResponse)(nil),                  // 5: models.AdminInfoResponse
	(*APISuccessGetUserByEmailResponse)(nil),   // 6: models.APISuccessGetUserByEmailResponse
	(*APISuccessGetWakatimeStatsResponse)(nil), // 7: models.APISuccessGetWakatimeStatsResponse
	(*entities.Guestbook)(nil),                 // 8: entities.Guestbook
	(*entities.User)(nil),                      // 9: entities.User
	(*entities.WakaTimeData)(nil),              // 10: entities.WakaTimeData
}
var file_pkg_models_response_proto_depIdxs = []int32{
	8,  // 0: models.APISuccessGetGuestbookResponse.data:type_name -> entities.Guestbook
	9,  // 1: models.APISuccessGetUserByEmailResponse.data:type_name -> entities.User
	10, // 2: models.APISuccessGetWakatimeStatsResponse.data:type_name -> entities.WakaTimeData
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_models_response_proto_init() }
func file_pkg_models_response_proto_init() {
	if File_pkg_models_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_models_response_proto_rawDesc), len(file_pkg_models_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_models_response_proto_goTypes,
		DependencyIndexes: file_pkg_models_response_proto_depIdxs,
		MessageInfos:      file_pkg_models_response_proto_msgTypes,
	}.Build()
	File_pkg_models_response_proto = out.File
	file_pkg_models_response_proto_goTypes = nil
	file_pkg_models_response_proto_depIdxs = nil
}
