// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.19.6
// source: pkg/entities/env.proto

package entities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnvVariables struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ADMIN_EMAIL        string                 `protobuf:"bytes,1,opt,name=ADMIN_EMAIL,json=ADMINEMAIL,proto3" json:"ADMIN_EMAIL,omitempty"`
	ADMIN_PASSWORD     string                 `protobuf:"bytes,2,opt,name=ADMIN_PASSWORD,json=ADMINPASSWORD,proto3" json:"ADMIN_PASSWORD,omitempty"`
	JWT_SECRET         string                 `protobuf:"bytes,3,opt,name=JWT_SECRET,json=JWTSECRET,proto3" json:"JWT_SECRET,omitempty"`
	TURSO_AUTH_TOKEN   string                 `protobuf:"bytes,4,opt,name=TURSO_AUTH_TOKEN,json=TURSOAUTHTOKEN,proto3" json:"TURSO_AUTH_TOKEN,omitempty"`
	TURSO_DATABASE_URL string                 `protobuf:"bytes,5,opt,name=TURSO_DATABASE_URL,json=TURSODATABASEURL,proto3" json:"TURSO_DATABASE_URL,omitempty"`
	WAKATIME_API_KEY   string                 `protobuf:"bytes,6,opt,name=WAKATIME_API_KEY,json=WAKATIMEAPIKEY,proto3" json:"WAKATIME_API_KEY,omitempty"`
	WAKATIME_API_URL   string                 `protobuf:"bytes,7,opt,name=WAKATIME_API_URL,json=WAKATIMEAPIURL,proto3" json:"WAKATIME_API_URL,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EnvVariables) Reset() {
	*x = EnvVariables{}
	mi := &file_pkg_entities_env_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvVariables) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvVariables) ProtoMessage() {}

func (x *EnvVariables) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_entities_env_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvVariables.ProtoReflect.Descriptor instead.
func (*EnvVariables) Descriptor() ([]byte, []int) {
	return file_pkg_entities_env_proto_rawDescGZIP(), []int{0}
}

func (x *EnvVariables) GetADMIN_EMAIL() string {
	if x != nil {
		return x.ADMIN_EMAIL
	}
	return ""
}

func (x *EnvVariables) GetADMIN_PASSWORD() string {
	if x != nil {
		return x.ADMIN_PASSWORD
	}
	return ""
}

func (x *EnvVariables) GetJWT_SECRET() string {
	if x != nil {
		return x.JWT_SECRET
	}
	return ""
}

func (x *EnvVariables) GetTURSO_AUTH_TOKEN() string {
	if x != nil {
		return x.TURSO_AUTH_TOKEN
	}
	return ""
}

func (x *EnvVariables) GetTURSO_DATABASE_URL() string {
	if x != nil {
		return x.TURSO_DATABASE_URL
	}
	return ""
}

func (x *EnvVariables) GetWAKATIME_API_KEY() string {
	if x != nil {
		return x.WAKATIME_API_KEY
	}
	return ""
}

func (x *EnvVariables) GetWAKATIME_API_URL() string {
	if x != nil {
		return x.WAKATIME_API_URL
	}
	return ""
}

var File_pkg_entities_env_proto protoreflect.FileDescriptor

const file_pkg_entities_env_proto_rawDesc = "" +
	"\n" +
	"\x16pkg/entities/env.proto\x12\bentities\"\xa1\x02\n" +
	"\fEnvVariables\x12\x1f\n" +
	"\vADMIN_EMAIL\x18\x01 \x01(\tR\n" +
	"ADMINEMAIL\x12%\n" +
	"\x0eADMIN_PASSWORD\x18\x02 \x01(\tR\rADMINPASSWORD\x12\x1d\n" +
	"\n" +
	"JWT_SECRET\x18\x03 \x01(\tR\tJWTSECRET\x12(\n" +
	"\x10TURSO_AUTH_TOKEN\x18\x04 \x01(\tR\x0eTURSOAUTHTOKEN\x12,\n" +
	"\x12TURSO_DATABASE_URL\x18\x05 \x01(\tR\x10TURSODATABASEURL\x12(\n" +
	"\x10WAKATIME_API_KEY\x18\x06 \x01(\tR\x0eWAKATIMEAPIKEY\x12(\n" +
	"\x10WAKATIME_API_URL\x18\a \x01(\tR\x0eWAKATIMEAPIURLB\x1bZ\x19ekel-backend/pkg/entitiesb\x06proto3"

var (
	file_pkg_entities_env_proto_rawDescOnce sync.Once
	file_pkg_entities_env_proto_rawDescData []byte
)

func file_pkg_entities_env_proto_rawDescGZIP() []byte {
	file_pkg_entities_env_proto_rawDescOnce.Do(func() {
		file_pkg_entities_env_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_entities_env_proto_rawDesc), len(file_pkg_entities_env_proto_rawDesc)))
	})
	return file_pkg_entities_env_proto_rawDescData
}

var file_pkg_entities_env_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_entities_env_proto_goTypes = []any{
	(*EnvVariables)(nil), // 0: entities.EnvVariables
}
var file_pkg_entities_env_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_entities_env_proto_init() }
func file_pkg_entities_env_proto_init() {
	if File_pkg_entities_env_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_entities_env_proto_rawDesc), len(file_pkg_entities_env_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_entities_env_proto_goTypes,
		DependencyIndexes: file_pkg_entities_env_proto_depIdxs,
		MessageInfos:      file_pkg_entities_env_proto_msgTypes,
	}.Build()
	File_pkg_entities_env_proto = out.File
	file_pkg_entities_env_proto_goTypes = nil
	file_pkg_entities_env_proto_depIdxs = nil
}
