// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.19.6
// source: pkg/entities/wakatime.proto

package entities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WakaTimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *WakaTimeData          `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WakaTimeResponse) Reset() {
	*x = WakaTimeResponse{}
	mi := &file_pkg_entities_wakatime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WakaTimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WakaTimeResponse) ProtoMessage() {}

func (x *WakaTimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_entities_wakatime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WakaTimeResponse.ProtoReflect.Descriptor instead.
func (*WakaTimeResponse) Descriptor() ([]byte, []int) {
	return file_pkg_entities_wakatime_proto_rawDescGZIP(), []int{0}
}

func (x *WakaTimeResponse) GetData() *WakaTimeData {
	if x != nil {
		return x.Data
	}
	return nil
}

type WakaTimeData struct {
	state                                           protoimpl.MessageState `protogen:"open.v1"`
	Id                                              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId                                          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Range                                           string                 `protobuf:"bytes,3,opt,name=range,proto3" json:"range,omitempty"`
	Timeout                                         int32                  `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	WritesOnly                                      bool                   `protobuf:"varint,5,opt,name=writes_only,json=writesOnly,proto3" json:"writes_only,omitempty"`
	Holidays                                        int32                  `protobuf:"varint,6,opt,name=holidays,proto3" json:"holidays,omitempty"`
	Status                                          string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	DaysIncludingHolidays                           int32                  `protobuf:"varint,8,opt,name=days_including_holidays,json=daysIncludingHolidays,proto3" json:"days_including_holidays,omitempty"`
	Languages                                       []*Language            `protobuf:"bytes,9,rep,name=languages,proto3" json:"languages,omitempty"`
	HumanReadableTotalIncludingOtherLanguage        string                 `protobuf:"bytes,10,opt,name=human_readable_total_including_other_language,json=humanReadableTotalIncludingOtherLanguage,proto3" json:"human_readable_total_including_other_language,omitempty"`
	TotalSecondsIncludingOtherLanguage              float64                `protobuf:"fixed64,11,opt,name=total_seconds_including_other_language,json=totalSecondsIncludingOtherLanguage,proto3" json:"total_seconds_including_other_language,omitempty"`
	TotalSeconds                                    float64                `protobuf:"fixed64,12,opt,name=total_seconds,json=totalSeconds,proto3" json:"total_seconds,omitempty"`
	IsAlreadyUpdating                               bool                   `protobuf:"varint,13,opt,name=is_already_updating,json=isAlreadyUpdating,proto3" json:"is_already_updating,omitempty"`
	DaysMinusHolidays                               int32                  `protobuf:"varint,14,opt,name=days_minus_holidays,json=daysMinusHolidays,proto3" json:"days_minus_holidays,omitempty"`
	DailyAverageIncludingOtherLanguage              float64                `protobuf:"fixed64,15,opt,name=daily_average_including_other_language,json=dailyAverageIncludingOtherLanguage,proto3" json:"daily_average_including_other_language,omitempty"`
	IsUpToDate                                      bool                   `protobuf:"varint,16,opt,name=is_up_to_date,json=isUpToDate,proto3" json:"is_up_to_date,omitempty"`
	OperatingSystems                                []*OperatingSystem     `protobuf:"bytes,17,rep,name=operating_systems,json=operatingSystems,proto3" json:"operating_systems,omitempty"`
	IsStuck                                         bool                   `protobuf:"varint,18,opt,name=is_stuck,json=isStuck,proto3" json:"is_stuck,omitempty"`
	IsUpToDatePendingFuture                         bool                   `protobuf:"varint,19,opt,name=is_up_to_date_pending_future,json=isUpToDatePendingFuture,proto3" json:"is_up_to_date_pending_future,omitempty"`
	HumanReadableTotal                              string                 `protobuf:"bytes,20,opt,name=human_readable_total,json=humanReadableTotal,proto3" json:"human_readable_total,omitempty"`
	HumanReadableDailyAverageIncludingOtherLanguage string                 `protobuf:"bytes,21,opt,name=human_readable_daily_average_including_other_language,json=humanReadableDailyAverageIncludingOtherLanguage,proto3" json:"human_readable_daily_average_including_other_language,omitempty"`
	HumanReadableDailyAverage                       string                 `protobuf:"bytes,22,opt,name=human_readable_daily_average,json=humanReadableDailyAverage,proto3" json:"human_readable_daily_average,omitempty"`
	DailyAverage                                    float64                `protobuf:"fixed64,23,opt,name=daily_average,json=dailyAverage,proto3" json:"daily_average,omitempty"`
	Categories                                      []*Category            `protobuf:"bytes,24,rep,name=categories,proto3" json:"categories,omitempty"`
	PercentCalculated                               int32                  `protobuf:"varint,25,opt,name=percent_calculated,json=percentCalculated,proto3" json:"percent_calculated,omitempty"`
	Editors                                         []*Editor              `protobuf:"bytes,26,rep,name=editors,proto3" json:"editors,omitempty"`
	IsCached                                        bool                   `protobuf:"varint,27,opt,name=is_cached,json=isCached,proto3" json:"is_cached,omitempty"`
	Username                                        string                 `protobuf:"bytes,28,opt,name=username,proto3" json:"username,omitempty"`
	IsIncludingToday                                bool                   `protobuf:"varint,29,opt,name=is_including_today,json=isIncludingToday,proto3" json:"is_including_today,omitempty"`
	HumanReadableRange                              string                 `protobuf:"bytes,30,opt,name=human_readable_range,json=humanReadableRange,proto3" json:"human_readable_range,omitempty"`
	IsCodingActivityVisible                         bool                   `protobuf:"varint,31,opt,name=is_coding_activity_visible,json=isCodingActivityVisible,proto3" json:"is_coding_activity_visible,omitempty"`
	IsLanguageUsageVisible                          bool                   `protobuf:"varint,32,opt,name=is_language_usage_visible,json=isLanguageUsageVisible,proto3" json:"is_language_usage_visible,omitempty"`
	IsEditorUsageVisible                            bool                   `protobuf:"varint,33,opt,name=is_editor_usage_visible,json=isEditorUsageVisible,proto3" json:"is_editor_usage_visible,omitempty"`
	IsCategoryUsageVisible                          bool                   `protobuf:"varint,34,opt,name=is_category_usage_visible,json=isCategoryUsageVisible,proto3" json:"is_category_usage_visible,omitempty"`
	IsOsUsageVisible                                bool                   `protobuf:"varint,35,opt,name=is_os_usage_visible,json=isOsUsageVisible,proto3" json:"is_os_usage_visible,omitempty"`
	unknownFields                                   protoimpl.UnknownFields
	sizeCache                                       protoimpl.SizeCache
}

func (x *WakaTimeData) Reset() {
	*x = WakaTimeData{}
	mi := &file_pkg_entities_wakatime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WakaTimeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WakaTimeData) ProtoMessage() {}

func (x *WakaTimeData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_entities_wakatime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WakaTimeData.ProtoReflect.Descriptor instead.
func (*WakaTimeData) Descriptor() ([]byte, []int) {
	return file_pkg_entities_wakatime_proto_rawDescGZIP(), []int{1}
}

func (x *WakaTimeData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WakaTimeData) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *WakaTimeData) GetRange() string {
	if x != nil {
		return x.Range
	}
	return ""
}

func (x *WakaTimeData) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *WakaTimeData) GetWritesOnly() bool {
	if x != nil {
		return x.WritesOnly
	}
	return false
}

func (x *WakaTimeData) GetHolidays() int32 {
	if x != nil {
		return x.Holidays
	}
	return 0
}

func (x *WakaTimeData) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WakaTimeData) GetDaysIncludingHolidays() int32 {
	if x != nil {
		return x.DaysIncludingHolidays
	}
	return 0
}

func (x *WakaTimeData) GetLanguages() []*Language {
	if x != nil {
		return x.Languages
	}
	return nil
}

func (x *WakaTimeData) GetHumanReadableTotalIncludingOtherLanguage() string {
	if x != nil {
		return x.HumanReadableTotalIncludingOtherLanguage
	}
	return ""
}

func (x *WakaTimeData) GetTotalSecondsIncludingOtherLanguage() float64 {
	if x != nil {
		return x.TotalSecondsIncludingOtherLanguage
	}
	return 0
}

func (x *WakaTimeData) GetTotalSeconds() float64 {
	if x != nil {
		return x.TotalSeconds
	}
	return 0
}

func (x *WakaTimeData) GetIsAlreadyUpdating() bool {
	if x != nil {
		return x.IsAlreadyUpdating
	}
	return false
}

func (x *WakaTimeData) GetDaysMinusHolidays() int32 {
	if x != nil {
		return x.DaysMinusHolidays
	}
	return 0
}

func (x *WakaTimeData) GetDailyAverageIncludingOtherLanguage() float64 {
	if x != nil {
		return x.DailyAverageIncludingOtherLanguage
	}
	return 0
}

func (x *WakaTimeData) GetIsUpToDate() bool {
	if x != nil {
		return x.IsUpToDate
	}
	return false
}

func (x *WakaTimeData) GetOperatingSystems() []*OperatingSystem {
	if x != nil {
		return x.OperatingSystems
	}
	return nil
}

func (x *WakaTimeData) GetIsStuck() bool {
	if x != nil {
		return x.IsStuck
	}
	return false
}

func (x *WakaTimeData) GetIsUpToDatePendingFuture() bool {
	if x != nil {
		return x.IsUpToDatePendingFuture
	}
	return false
}

func (x *WakaTimeData) GetHumanReadableTotal() string {
	if x != nil {
		return x.HumanReadableTotal
	}
	return ""
}

func (x *WakaTimeData) GetHumanReadableDailyAverageIncludingOtherLanguage() string {
	if x != nil {
		return x.HumanReadableDailyAverageIncludingOtherLanguage
	}
	return ""
}

func (x *WakaTimeData) GetHumanReadableDailyAverage() string {
	if x != nil {
		return x.HumanReadableDailyAverage
	}
	return ""
}

func (x *WakaTimeData) GetDailyAverage() float64 {
	if x != nil {
		return x.DailyAverage
	}
	return 0
}

func (x *WakaTimeData) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *WakaTimeData) GetPercentCalculated() int32 {
	if x != nil {
		return x.PercentCalculated
	}
	return 0
}

func (x *WakaTimeData) GetEditors() []*Editor {
	if x != nil {
		return x.Editors
	}
	return nil
}

func (x *WakaTimeData) GetIsCached() bool {
	if x != nil {
		return x.IsCached
	}
	return false
}

func (x *WakaTimeData) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *WakaTimeData) GetIsIncludingToday() bool {
	if x != nil {
		return x.IsIncludingToday
	}
	return false
}

func (x *WakaTimeData) GetHumanReadableRange() string {
	if x != nil {
		return x.HumanReadableRange
	}
	return ""
}

func (x *WakaTimeData) GetIsCodingActivityVisible() bool {
	if x != nil {
		return x.IsCodingActivityVisible
	}
	return false
}

func (x *WakaTimeData) GetIsLanguageUsageVisible() bool {
	if x != nil {
		return x.IsLanguageUsageVisible
	}
	return false
}

func (x *WakaTimeData) GetIsEditorUsageVisible() bool {
	if x != nil {
		return x.IsEditorUsageVisible
	}
	return false
}

func (x *WakaTimeData) GetIsCategoryUsageVisible() bool {
	if x != nil {
		return x.IsCategoryUsageVisible
	}
	return false
}

func (x *WakaTimeData) GetIsOsUsageVisible() bool {
	if x != nil {
		return x.IsOsUsageVisible
	}
	return false
}

type Language struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TotalSeconds  float64                `protobuf:"fixed64,2,opt,name=total_seconds,json=totalSeconds,proto3" json:"total_seconds,omitempty"`
	Percent       float64                `protobuf:"fixed64,3,opt,name=percent,proto3" json:"percent,omitempty"`
	Digital       string                 `protobuf:"bytes,4,opt,name=digital,proto3" json:"digital,omitempty"`
	Decimal       string                 `protobuf:"bytes,5,opt,name=decimal,proto3" json:"decimal,omitempty"`
	Text          string                 `protobuf:"bytes,6,opt,name=text,proto3" json:"text,omitempty"`
	Hours         int32                  `protobuf:"varint,7,opt,name=hours,proto3" json:"hours,omitempty"`
	Minutes       int32                  `protobuf:"varint,8,opt,name=minutes,proto3" json:"minutes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Language) Reset() {
	*x = Language{}
	mi := &file_pkg_entities_wakatime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Language) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Language) ProtoMessage() {}

func (x *Language) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_entities_wakatime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Language.ProtoReflect.Descriptor instead.
func (*Language) Descriptor() ([]byte, []int) {
	return file_pkg_entities_wakatime_proto_rawDescGZIP(), []int{2}
}

func (x *Language) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Language) GetTotalSeconds() float64 {
	if x != nil {
		return x.TotalSeconds
	}
	return 0
}

func (x *Language) GetPercent() float64 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *Language) GetDigital() string {
	if x != nil {
		return x.Digital
	}
	return ""
}

func (x *Language) GetDecimal() string {
	if x != nil {
		return x.Decimal
	}
	return ""
}

func (x *Language) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Language) GetHours() int32 {
	if x != nil {
		return x.Hours
	}
	return 0
}

func (x *Language) GetMinutes() int32 {
	if x != nil {
		return x.Minutes
	}
	return 0
}

type OperatingSystem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TotalSeconds  float64                `protobuf:"fixed64,2,opt,name=total_seconds,json=totalSeconds,proto3" json:"total_seconds,omitempty"`
	Percent       float64                `protobuf:"fixed64,3,opt,name=percent,proto3" json:"percent,omitempty"`
	Digital       string                 `protobuf:"bytes,4,opt,name=digital,proto3" json:"digital,omitempty"`
	Decimal       string                 `protobuf:"bytes,5,opt,name=decimal,proto3" json:"decimal,omitempty"`
	Text          string                 `protobuf:"bytes,6,opt,name=text,proto3" json:"text,omitempty"`
	Hours         int32                  `protobuf:"varint,7,opt,name=hours,proto3" json:"hours,omitempty"`
	Minutes       int32                  `protobuf:"varint,8,opt,name=minutes,proto3" json:"minutes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperatingSystem) Reset() {
	*x = OperatingSystem{}
	mi := &file_pkg_entities_wakatime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatingSystem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatingSystem) ProtoMessage() {}

func (x *OperatingSystem) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_entities_wakatime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatingSystem.ProtoReflect.Descriptor instead.
func (*OperatingSystem) Descriptor() ([]byte, []int) {
	return file_pkg_entities_wakatime_proto_rawDescGZIP(), []int{3}
}

func (x *OperatingSystem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OperatingSystem) GetTotalSeconds() float64 {
	if x != nil {
		return x.TotalSeconds
	}
	return 0
}

func (x *OperatingSystem) GetPercent() float64 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *OperatingSystem) GetDigital() string {
	if x != nil {
		return x.Digital
	}
	return ""
}

func (x *OperatingSystem) GetDecimal() string {
	if x != nil {
		return x.Decimal
	}
	return ""
}

func (x *OperatingSystem) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *OperatingSystem) GetHours() int32 {
	if x != nil {
		return x.Hours
	}
	return 0
}

func (x *OperatingSystem) GetMinutes() int32 {
	if x != nil {
		return x.Minutes
	}
	return 0
}

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TotalSeconds  float64                `protobuf:"fixed64,2,opt,name=total_seconds,json=totalSeconds,proto3" json:"total_seconds,omitempty"`
	Percent       float64                `protobuf:"fixed64,3,opt,name=percent,proto3" json:"percent,omitempty"`
	Digital       string                 `protobuf:"bytes,4,opt,name=digital,proto3" json:"digital,omitempty"`
	Decimal       string                 `protobuf:"bytes,5,opt,name=decimal,proto3" json:"decimal,omitempty"`
	Text          string                 `protobuf:"bytes,6,opt,name=text,proto3" json:"text,omitempty"`
	Hours         int32                  `protobuf:"varint,7,opt,name=hours,proto3" json:"hours,omitempty"`
	Minutes       int32                  `protobuf:"varint,8,opt,name=minutes,proto3" json:"minutes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_pkg_entities_wakatime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_entities_wakatime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_pkg_entities_wakatime_proto_rawDescGZIP(), []int{4}
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetTotalSeconds() float64 {
	if x != nil {
		return x.TotalSeconds
	}
	return 0
}

func (x *Category) GetPercent() float64 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *Category) GetDigital() string {
	if x != nil {
		return x.Digital
	}
	return ""
}

func (x *Category) GetDecimal() string {
	if x != nil {
		return x.Decimal
	}
	return ""
}

func (x *Category) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Category) GetHours() int32 {
	if x != nil {
		return x.Hours
	}
	return 0
}

func (x *Category) GetMinutes() int32 {
	if x != nil {
		return x.Minutes
	}
	return 0
}

type Editor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TotalSeconds  float64                `protobuf:"fixed64,2,opt,name=total_seconds,json=totalSeconds,proto3" json:"total_seconds,omitempty"`
	Percent       float64                `protobuf:"fixed64,3,opt,name=percent,proto3" json:"percent,omitempty"`
	Digital       string                 `protobuf:"bytes,4,opt,name=digital,proto3" json:"digital,omitempty"`
	Decimal       string                 `protobuf:"bytes,5,opt,name=decimal,proto3" json:"decimal,omitempty"`
	Text          string                 `protobuf:"bytes,6,opt,name=text,proto3" json:"text,omitempty"`
	Hours         int32                  `protobuf:"varint,7,opt,name=hours,proto3" json:"hours,omitempty"`
	Minutes       int32                  `protobuf:"varint,8,opt,name=minutes,proto3" json:"minutes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Editor) Reset() {
	*x = Editor{}
	mi := &file_pkg_entities_wakatime_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Editor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Editor) ProtoMessage() {}

func (x *Editor) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_entities_wakatime_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Editor.ProtoReflect.Descriptor instead.
func (*Editor) Descriptor() ([]byte, []int) {
	return file_pkg_entities_wakatime_proto_rawDescGZIP(), []int{5}
}

func (x *Editor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Editor) GetTotalSeconds() float64 {
	if x != nil {
		return x.TotalSeconds
	}
	return 0
}

func (x *Editor) GetPercent() float64 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *Editor) GetDigital() string {
	if x != nil {
		return x.Digital
	}
	return ""
}

func (x *Editor) GetDecimal() string {
	if x != nil {
		return x.Decimal
	}
	return ""
}

func (x *Editor) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Editor) GetHours() int32 {
	if x != nil {
		return x.Hours
	}
	return 0
}

func (x *Editor) GetMinutes() int32 {
	if x != nil {
		return x.Minutes
	}
	return 0
}

var File_pkg_entities_wakatime_proto protoreflect.FileDescriptor

const file_pkg_entities_wakatime_proto_rawDesc = "" +
	"\n" +
	"\x1bpkg/entities/wakatime.proto\x12\bentities\">\n" +
	"\x10WakaTimeResponse\x12*\n" +
	"\x04data\x18\x01 \x01(\v2\x16.entities.WakaTimeDataR\x04data\"\xc2\r\n" +
	"\fWakaTimeData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05range\x18\x03 \x01(\tR\x05range\x12\x18\n" +
	"\atimeout\x18\x04 \x01(\x05R\atimeout\x12\x1f\n" +
	"\vwrites_only\x18\x05 \x01(\bR\n" +
	"writesOnly\x12\x1a\n" +
	"\bholidays\x18\x06 \x01(\x05R\bholidays\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x126\n" +
	"\x17days_including_holidays\x18\b \x01(\x05R\x15daysIncludingHolidays\x120\n" +
	"\tlanguages\x18\t \x03(\v2\x12.entities.LanguageR\tlanguages\x12_\n" +
	"-human_readable_total_including_other_language\x18\n" +
	" \x01(\tR(humanReadableTotalIncludingOtherLanguage\x12R\n" +
	"&total_seconds_including_other_language\x18\v \x01(\x01R\"totalSecondsIncludingOtherLanguage\x12#\n" +
	"\rtotal_seconds\x18\f \x01(\x01R\ftotalSeconds\x12.\n" +
	"\x13is_already_updating\x18\r \x01(\bR\x11isAlreadyUpdating\x12.\n" +
	"\x13days_minus_holidays\x18\x0e \x01(\x05R\x11daysMinusHolidays\x12R\n" +
	"&daily_average_including_other_language\x18\x0f \x01(\x01R\"dailyAverageIncludingOtherLanguage\x12!\n" +
	"\ris_up_to_date\x18\x10 \x01(\bR\n" +
	"isUpToDate\x12F\n" +
	"\x11operating_systems\x18\x11 \x03(\v2\x19.entities.OperatingSystemR\x10operatingSystems\x12\x19\n" +
	"\bis_stuck\x18\x12 \x01(\bR\aisStuck\x12=\n" +
	"\x1cis_up_to_date_pending_future\x18\x13 \x01(\bR\x17isUpToDatePendingFuture\x120\n" +
	"\x14human_readable_total\x18\x14 \x01(\tR\x12humanReadableTotal\x12n\n" +
	"5human_readable_daily_average_including_other_language\x18\x15 \x01(\tR/humanReadableDailyAverageIncludingOtherLanguage\x12?\n" +
	"\x1chuman_readable_daily_average\x18\x16 \x01(\tR\x19humanReadableDailyAverage\x12#\n" +
	"\rdaily_average\x18\x17 \x01(\x01R\fdailyAverage\x122\n" +
	"\n" +
	"categories\x18\x18 \x03(\v2\x12.entities.CategoryR\n" +
	"categories\x12-\n" +
	"\x12percent_calculated\x18\x19 \x01(\x05R\x11percentCalculated\x12*\n" +
	"\aeditors\x18\x1a \x03(\v2\x10.entities.EditorR\aeditors\x12\x1b\n" +
	"\tis_cached\x18\x1b \x01(\bR\bisCached\x12\x1a\n" +
	"\busername\x18\x1c \x01(\tR\busername\x12,\n" +
	"\x12is_including_today\x18\x1d \x01(\bR\x10isIncludingToday\x120\n" +
	"\x14human_readable_range\x18\x1e \x01(\tR\x12humanReadableRange\x12;\n" +
	"\x1ais_coding_activity_visible\x18\x1f \x01(\bR\x17isCodingActivityVisible\x129\n" +
	"\x19is_language_usage_visible\x18  \x01(\bR\x16isLanguageUsageVisible\x125\n" +
	"\x17is_editor_usage_visible\x18! \x01(\bR\x14isEditorUsageVisible\x129\n" +
	"\x19is_category_usage_visible\x18\" \x01(\bR\x16isCategoryUsageVisible\x12-\n" +
	"\x13is_os_usage_visible\x18# \x01(\bR\x10isOsUsageVisible\"\xd5\x01\n" +
	"\bLanguage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rtotal_seconds\x18\x02 \x01(\x01R\ftotalSeconds\x12\x18\n" +
	"\apercent\x18\x03 \x01(\x01R\apercent\x12\x18\n" +
	"\adigital\x18\x04 \x01(\tR\adigital\x12\x18\n" +
	"\adecimal\x18\x05 \x01(\tR\adecimal\x12\x12\n" +
	"\x04text\x18\x06 \x01(\tR\x04text\x12\x14\n" +
	"\x05hours\x18\a \x01(\x05R\x05hours\x12\x18\n" +
	"\aminutes\x18\b \x01(\x05R\aminutes\"\xdc\x01\n" +
	"\x0fOperatingSystem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rtotal_seconds\x18\x02 \x01(\x01R\ftotalSeconds\x12\x18\n" +
	"\apercent\x18\x03 \x01(\x01R\apercent\x12\x18\n" +
	"\adigital\x18\x04 \x01(\tR\adigital\x12\x18\n" +
	"\adecimal\x18\x05 \x01(\tR\adecimal\x12\x12\n" +
	"\x04text\x18\x06 \x01(\tR\x04text\x12\x14\n" +
	"\x05hours\x18\a \x01(\x05R\x05hours\x12\x18\n" +
	"\aminutes\x18\b \x01(\x05R\aminutes\"\xd5\x01\n" +
	"\bCategory\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rtotal_seconds\x18\x02 \x01(\x01R\ftotalSeconds\x12\x18\n" +
	"\apercent\x18\x03 \x01(\x01R\apercent\x12\x18\n" +
	"\adigital\x18\x04 \x01(\tR\adigital\x12\x18\n" +
	"\adecimal\x18\x05 \x01(\tR\adecimal\x12\x12\n" +
	"\x04text\x18\x06 \x01(\tR\x04text\x12\x14\n" +
	"\x05hours\x18\a \x01(\x05R\x05hours\x12\x18\n" +
	"\aminutes\x18\b \x01(\x05R\aminutes\"\xd3\x01\n" +
	"\x06Editor\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rtotal_seconds\x18\x02 \x01(\x01R\ftotalSeconds\x12\x18\n" +
	"\apercent\x18\x03 \x01(\x01R\apercent\x12\x18\n" +
	"\adigital\x18\x04 \x01(\tR\adigital\x12\x18\n" +
	"\adecimal\x18\x05 \x01(\tR\adecimal\x12\x12\n" +
	"\x04text\x18\x06 \x01(\tR\x04text\x12\x14\n" +
	"\x05hours\x18\a \x01(\x05R\x05hours\x12\x18\n" +
	"\aminutes\x18\b \x01(\x05R\aminutesB\x1bZ\x19ekel-backend/pkg/entitiesb\x06proto3"

var (
	file_pkg_entities_wakatime_proto_rawDescOnce sync.Once
	file_pkg_entities_wakatime_proto_rawDescData []byte
)

func file_pkg_entities_wakatime_proto_rawDescGZIP() []byte {
	file_pkg_entities_wakatime_proto_rawDescOnce.Do(func() {
		file_pkg_entities_wakatime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_entities_wakatime_proto_rawDesc), len(file_pkg_entities_wakatime_proto_rawDesc)))
	})
	return file_pkg_entities_wakatime_proto_rawDescData
}

var file_pkg_entities_wakatime_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_entities_wakatime_proto_goTypes = []any{
	(*WakaTimeResponse)(nil), // 0: entities.WakaTimeResponse
	(*WakaTimeData)(nil),     // 1: entities.WakaTimeData
	(*Language)(nil),         // 2: entities.Language
	(*OperatingSystem)(nil),  // 3: entities.OperatingSystem
	(*Category)(nil),         // 4: entities.Category
	(*Editor)(nil),           // 5: entities.Editor
}
var file_pkg_entities_wakatime_proto_depIdxs = []int32{
	1, // 0: entities.WakaTimeResponse.data:type_name -> entities.WakaTimeData
	2, // 1: entities.WakaTimeData.languages:type_name -> entities.Language
	3, // 2: entities.WakaTimeData.operating_systems:type_name -> entities.OperatingSystem
	4, // 3: entities.WakaTimeData.categories:type_name -> entities.Category
	5, // 4: entities.WakaTimeData.editors:type_name -> entities.Editor
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_entities_wakatime_proto_init() }
func file_pkg_entities_wakatime_proto_init() {
	if File_pkg_entities_wakatime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_entities_wakatime_proto_rawDesc), len(file_pkg_entities_wakatime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_entities_wakatime_proto_goTypes,
		DependencyIndexes: file_pkg_entities_wakatime_proto_depIdxs,
		MessageInfos:      file_pkg_entities_wakatime_proto_msgTypes,
	}.Build()
	File_pkg_entities_wakatime_proto = out.File
	file_pkg_entities_wakatime_proto_goTypes = nil
	file_pkg_entities_wakatime_proto_depIdxs = nil
}
